### PR TITLE
pr_484

### PR DESCRIPTION
**Pull request by kalpaitch**
Pull request for issues - https://github.com/warmshowers/Warmshowers.org/issues/484

Resolved incorrect html formatting of username in feedback url/form.

### CODE REVIEW

**Comment by rfay** [comment]
You're awesome! Congrats on first PR. 

There are a couple of things:

* Please make sure that you address only one issue in each PR (you did both the username thing and the .gitignore here, which related to #519)
* Please give the PR a descriptive title
* For most of the work you do at this point, please create PRs against the site_d7 branch, since we're really actively trying to make that work.

Your fix looks perfect. If you want to commit it here without the .gitignore change (the fix has already been made in site_d7 (#519, https://github.com/warmshowers/Warmshowers.org/commit/9fcc5ecd0ece1972105b599f175778ca9da21c60) - note that in d7 docroot/.gitignore excludes settings*.php.

I'm going to go ahead and pull this and then cherry-pick the $account->name fix into site_d7.

**Comment by rfay** [comment]
Cherry-picked onto site_d7 with https://github.com/warmshowers/Warmshowers.org/commit/f879bf14c3b95661faf94eecd24e296635542489

**Comment by rfay** [comment]
Deployed onto site.

**Comment by kalpaitch** [comment]
Sure thing, affirmative on the bullets.

**Pull request merged**
