### PR TITLE
20151009 css multiplefixes

### PR DESCRIPTION
**Pull request by jeanfrancoisbeaulieu**
New Anon Dashboard look and feel, with new bigger slideshow and re-worked disposition.

Deploy:
- disable old 'unauthenticated_front' context in Context
- enable and revert the new feature : 'redesign_unauthenticated_front'
- enable block_class module
- enable output type to ddSlick at /admin/structure/block/manage/lang_dropdown/language/configure, and choose skin : 'Custom skin' with Custom skin name : 'ddsWS'
* compass compile
* drush cc all

Also changes: 
- new images for social media in the footer
- new language dropdown look using ddSlick library
- new map info window when browsing map.
- new colors and better color organisation

### CODE REVIEW

**Comment by kalpaitch** [comment]
I found a bug with language_dropdowns admin page that blocked the ability to change jquery plugins. Let me check that one again. Nice work BTW.

**Comment by rfay** [comment]
We have your patch in there :)

**Comment by kalpaitch** [comment]
Really? Oh :)

**Comment by kalpaitch** [comment]
++++ Really awesome, perfect instructions, all good.

Attaching a screenshot of what I got, only thing I noticed is that in my browser (FF something on Ubuntu) the Warmshowers Community Welcome message is a little bit hidden. I don't think the image not showing is a problem it's probably that I don't have stage_proxy enabled or something simple.

Also one small point, I just wondered whether we need the id selector in `.page-frontpage.not-logged-in #content-area .block-howitworks ol`, just a question??

initial

**Comment by jeanfrancoisbeaulieu** [comment]
Oh, didn't see the notification for this, sorry. 

- Randy and I thought that this text should be shortened so that it can be displayed bigger then before. The current text is very lengthy imo. This will need support from translator before or at deploy.
- The slideshow's missing images should be resolve by stage_proxy. It's pointing to a single node that contains the selected images.
- The 'Mobile Apps' link do too, uses a new node that has a slightly different translation and has icons added in css.
- For the selector, no that's true, probably not. I tried to shorten selectors has I worked through the code, but it clearly wasn't exhaustive.

Let me now if you need any more help on this. I tend to miss github notifications so slack is better.

**Pull request merged**
