### PR TITLE
Probably fixes #892 so we can't get missing arg on mandrill_incoming_event

### LINKED ISSUE #892: PHP Warning: Missing argument in mandrill_incoming_event
https://www.wsupg.net/admin/reports/event/23291087

Warning: Missing argument 1 for mandrill_incoming_event() in mandrill_incoming_event() (line 146 of /var/www/wsupg.net/docroot/sites/all/modules/contrib/mandrill_incoming/mandrill_incoming.module).

### PR DESCRIPTION
**Pull request by rfay**
Simple fix for trivial (apparently) #892

### CODE REVIEW

**Comment by rfay** [comment]
Tested on wsupg, and think it's low risk. Does require drush cc all to deploy

**Comment by rfay** [comment]
This one does require watching on deploy. It should cause no harm, but it's worth watching the next few messages come through.

**Comment by kalpaitch** [comment]
I'm sure you are pushing to d.o as well, but in the mean time could we put a big flag on this, in the reader or something.

**Comment by rfay** [comment]
Thanks for the ping. I did push it up to d.o and was in fact afraid that I'd forget. I will update this to latest dev and also a patch landed in uc_optional_checkout_review.

Normally I would move something patched into the sites/all/modules/patched directory so I kind of violated my process on this one. I wanted to get some miles on it, but we've got (a few) miles now at least.

**Pull request merged**
