### PR TITLE
20150921 css fontsizes

### PR DESCRIPTION
**Pull request by jeanfrancoisbeaulieu**
Re-worked the Zen-Grid so it uses gutters properly. (adds half gutters on each side, reduces the content wide by 20px)
Re-styling text and header alignement, mostly on the Dashboard.

### CODE REVIEW

**Comment by rfay** [comment]
I only looked at it visually, but wanted to ask if the change to the main logo area was intentional:

home___warmshowers_org

**Comment by jeanfrancoisbeaulieu** [comment]
No, seems like the .header__site-name is missing font-size:70px; Must have missed a line in my commit.

**Comment by rfay** [comment]
Also, the map seems to have disappeared for some users:

home___warmshowers_org

**Comment by jeanfrancoisbeaulieu** [comment]
About the map, that doesn't happen before these commits? Do these users exists for me too?

**Comment by rfay** [comment]
Thanks!

**Pull request merged**
