### PR TITLE
Flag friends

### PR DESCRIPTION
**Pull request by ryssbowh**
Related to #27

Let's be slow to be sure we're on the same page... this is a pull request adding a new feature "Mark as favourite" that allows users to flag other users as favourites.
- Button "Mark/Unmark as favourite" on each user's profile page.
- Flagged users are displayed on each user's profile page under tab "Favourites" thanks to a view. Allow filtering on user's fullnames.
- Button "Favourites" in the welcome block.

Fixes/Improvements:
- Limit the access to user's own favourites only. At the moment the view doesn't show other users's favourites, but the tab is still displayed when visiting someone else's profile. Not possible to limit access of a view to the current user only (have to be hand-coded ?)
- Theme the flag links (on the favourites list of each user) as the others buttons. Recopy buttons's theme into the css theming this view ? The link is added in the view as a field and no way to add the proper css classes there.

And a general "how-to-do-best" question, always the same:
This feature on itself doesn't work, it depends on modifications in wsuser.module and wsuser-member-actions-block.tpl.php among others, is it an expected way of developing ?

### CODE REVIEW

**Comment by kalpaitch** [comment]
Hi, I'm going to be really fussy and say that is 'favourites'  the best way to describe a person? I might have called them 'buddies' or 'connections' #thinkingoutloud. 

Will get onto testing this feature when I can.

**Comment by rfay** [comment]
We're using "favorites" in the Android app now. But it's an open question.
They used to be "starred", but that didn't seem right. I think there are
several things that would work, but "buddies" is probably too familiar, and
"Connections" would get objections from people who don't want us to seem
like a social network :)  Keep the ideas coming!

Note that we'll have to figure out a way for "favorites" to be centralized
on the server and provided to the mobile apps.

Welcome!

-Randy

**Comment by kalpaitch** [comment]
Come on, that's not how you spell favourites ;)

I'm not familiar enough with Android to really comment but possibly something to expose as a service after the d7 upgrade.

**Comment by klzig** [comment]
On the WP app, you "pin" hosts that you want to remember and easily get back to later.  This is similar to the star in the previous android app, but I think a better metaphor.  It's also similar to a favourite in the iphone app-- I'm pretty sure all three are just different names/metaphors for the same thing.

I'm not keen on favourite, no matter how you spell it:)  At least on the phones, the process of remembering a member (usually a host) for later is not an act of endearment or popularity.  It's a convenience for a touring cyclist trying to manage many things on a tiny screen.  For example in the WP app, the author of an incoming message is automatically pinned chronologically so the cyclist can quickly find the members most relevant at the time.  It's up to the cyclist to decide, but in a week there may be an entirely different set of pinned hosts.

Another minor nit is that the grammar of favorites can get in the way.  It's pretty crisp to say that you're pinning a host and displaying pinned hosts.  Or even starring hosts and displaying starred hosts.  But there isn't a good verb for favorite-- I have to "add to favorites" or "make favorite" or something.  I guess I could "Favor" a host.

I agree that we don't want to take on the terminology or character of a social network.

If the consensus is that the term should be favorite, and that there is value in unifying this notion across all apps, it's an easy enough change for me.  But as we start talking about this on both the web site and mobile apps I wonder if we aren't talking about two different features.

**Comment by rfay** [comment]
I like "pin". We should think about that for everywhere. It may not fit in
the website context, but maybe it does.

**Pull request closed without merging**
