### PR TITLE
919: Removed exit from node view access check on search indexing.

### PR DESCRIPTION
**Pull request by kalpaitch**
Fixes: https://github.com/warmshowers/Warmshowers.org/issues/919

### CODE REVIEW

**Comment by kalpaitch** [comment]
Yea but I don't think that would have an effect on node teasers. Or when shown in views.

**Comment by rfay** [comment]
In views, you just make the view have appropriate perms, but I think it would work even without that. Pretty sure it would work for teasers.

**Comment by rfay** [comment]
I think this approach is a good one for now. I've tested, and it does what we want. 

I don't like the overall approach. It was a hack in D6, it's a hack here. Thanks for at least fixing the hack, and for debugging this. 

I guess it would have been a better approach to git bisect this, in retrospect, since it was so easy to see happen, and it appeared late in the process. I need to remember my friend git bisect!

I'll pull and deploy.

**Comment by rfay** [comment]
Deployed, cron set up. Thanks so much for this. I'm going to reopen the issue, but it's lower priority now and can replace this approach if we find a good way.

kalpaitch++

**Pull request merged**
