### PR TITLE
Port mandrill_incoming to D7

### LINKED ISSUE #496: D7: Port mandrill_incoming to D7 and get on drupal.org
The mandrill_incoming module was developed for WS, but has only a 6.x version on Drupal.org. Port to D7 and put at least a dev version on drupal.org

Testing of mandrill incoming stuff is a little complicated, as it requires a publicly accessible port.  I [wrote an article about tunnelling external webservice call](http://randyfay.com/content/tunneling-http-debug-or-develop-external-webservice-call) when originally doing this stuff to explain how to set up a development and testing environment.

### PR DESCRIPTION
**Pull request by kostajh**
This pull request fixes #496 (eventually).

This module is still pending testing, but creating the PR for feedback and review.

/cc @rfay @chrisarusso

### CODE REVIEW

**Comment by chrisarusso** [comment]
Nicely formatted!

**Comment by rfay** [comment]
Looking good to me. I won't pull it until you say to do so.

**Comment by kostajh** [comment]
@rfay I tested using [this technique](http://randyfay.com/content/tunneling-http-debug-or-develop-external-webservice-call) and the `$events` object is correctly passed to `ws_pm_email_notify`'s `hook_mandrill_incoming_event`. So, I think this is completed -- but have a look and let me know.

**Comment by rfay** [comment]
Could you do this as a patch into drupal.org, and it can be reviewed there, and I'll make you a committer, etc?

**Comment by kostajh** [comment]
@rfay yep

**Comment by kostajh** [comment]
@rfay all set! Please merge when you're ready.

**Comment by rfay** [comment]
I'll add it to the dependencies and push.

Thanks!

**Pull request merged**
