### PR TITLE
#521: Initial work on providing a smooth migration for service urls.

### PR DESCRIPTION
**Pull request by kalpaitch**
This is just an initial proposal on #521 to get your comment and hopefully get it into the current d6 site so that we can start updating the apps.

EDIT: Documentation in the process of being added to the wiki - https://github.com/warmshowers/Warmshowers.org/wiki/Warmshowers-RESTful-Services-for-Mobile-Apps#authenticate

### CODE REVIEW

**Comment by kalpaitch** [comment]
Just rethinking this and instead of providing a blank response from D6 and require apps to check for this and act appropriately, would it work to just have D6 provide a fake token and just add an X-CSRF-Token header regardless or whether Services needs it or not?? This would avoid apps having to make a check.

**Comment by rfay** [comment]
I agree that d6 should provide a response identical to d7, but it doesn't
have to have any particular value. That's the way I was thinking it could
work too.

**Comment by rfay** [comment]
I'm OK with this and will pull it if you like it, but it would be quite a bit more obvious to just do it using services module, as the few custom services provided in ws_services. It could just be added there and would take nearly nothing, and there's no risk of problematic differences in formatting or anything.

https://github.com/warmshowers/Warmshowers.org/blob/site/docroot/sites/all/modules/dev/ws_services/ws_services.module

And THANKS for making this happen.

**Comment by rfay** [comment]
Reviewing what they did in Services module for D7, I see you did exactly what they did, so let's go with this.

**Comment by rfay** [comment]
This is deployed on the site. #521 still stays open for a bit because we have to explain to the mobile devs what to do next.

**Pull request merged**
