### PR TITLE
Review of test features and creation of testing matrix

### PR DESCRIPTION
**Pull request by kalpaitch**
Reviewing all test features and making sure scenario titles are more human readable.

And creation of a Manual Testing Matrix - https://docs.google.com/spreadsheets/d/17ngPrGIK68R_hu5wGuA8RpvT4jswY8jf6_VBljUdZ6w/edit#gid=0

The idea is for this matrix to contain all test features and scenarios and to be a checklist for anyone testing the site. It should be ordered in the order we wish users to test the site.

@rfay please do not merge this pr yet, only half way through review, but comments welcome on any features/scenarios that might be left out, not accurate.

### CODE REVIEW

**Comment by rfay** [comment]
"Remember me" in the login feature was misunderstood as "remember username" when in fact it's "Stay logged in forever". That scenario should be updated to reflect that.

**Comment by kalpaitch** [comment]
Correct, I noticed that one and thought I'd changed. Thanks.

**Comment by kalpaitch** [comment]
@rfay I've been through most of the features by now and think some are looking like good candidates for automation which we can start to slowly work on after upgrade.

For now though this is really good documentation so would be good to see if you can see anything that's missing. I think particularly we need to add a few more around admin tasks, I'm not really aware of all the tasks that you folks do.

**Comment by rfay** [comment]
Pull when ready then.

The admin tasks *and* the translator tasks.

**Pull request merged**
